#!/usr/bin/env python3
"""Generate the sparse-input oracle fixture (catboost-8z4.44 / P3.7, part c).

Pins Python catboost==1.2.10's Pool construction and fit/predict output for a
Pool built from a scipy.sparse.csr_matrix, so R's new dgCMatrix input path can
be compared against the oracle's scipy-sparse path.

The stored values are baked into the fixture as a dense row list; both sides
rebuild their own sparse container from it (scipy CSR here, Matrix::dgCMatrix
in R), which keeps the fixture free of format-specific index/pointer arrays.

Note on the dataset: a degenerate mostly-zero matrix makes several split
candidates score-tied, and CatBoost's tie-breaking differs between its sparse
and dense column layouts (observed: max |dense - sparse| prediction delta
0.0298 on a 12x5 all-but-three-zeros matrix). The fixture therefore uses a
non-degenerate ~40%-filled matrix, on which the sparse and dense training
paths agree bit-for-bit; both are recorded below so the R test can assert
against the sparse path and the equality is auditable.

Run via: uv run --frozen --project tools/oracle python3 tools/oracle/gen_pool_sparse_fixture.py

Pass --degenerate to instead generate tests/fixtures/oracle/pool_sparse_degenerate.json,
a 12x5 tie-heavy matrix (one dense column, three extra non-zero cells outside
it) that reproduces the sparse-vs-dense tie-breaking divergence documented
above and in catboost-8z4.46: on this matrix, Python's own dense-Pool and
scipy.sparse.csr_matrix-Pool predictions disagree (max_sparse_dense_delta > 0),
unlike the non-degenerate fixture generated by default.
"""
import argparse
import json
import os
import sys

import numpy as np
import scipy.sparse as sp

from catboost import CatBoost, Pool
import catboost

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
FIXTURE_DIR = os.path.join(REPO_ROOT, "tests", "fixtures", "oracle")
FIXTURE_PATH = os.path.join(FIXTURE_DIR, "pool_sparse.json")
DEGENERATE_FIXTURE_PATH = os.path.join(FIXTURE_DIR, "pool_sparse_degenerate.json")

N_ROWS = 40
N_COLS = 6

PARAMS = {
    "loss_function": "Logloss",
    "iterations": 10,
    "depth": 3,
    "learning_rate": 0.3,
    "random_seed": 42,
    "thread_count": 1,
    "verbose": False,
}

DEGENERATE_N_ROWS = 12
DEGENERATE_N_COLS = 5

DEGENERATE_PARAMS = {
    "loss_function": "Logloss",
    "iterations": 1,
    "depth": 3,
    "learning_rate": 0.3,
    "random_seed": 42,
    "thread_count": 1,
    "verbose": False,
}


def build_dense():
    rng = np.random.RandomState(7)
    dense = np.zeros((N_ROWS, N_COLS))
    mask = rng.rand(N_ROWS, N_COLS) < 0.4
    dense[mask] = np.round(rng.randn(mask.sum()) * 2, 3)
    return dense


def build_dense_degenerate():
    """A 12x5, tie-heavy matrix: one dense column plus three extra non-zero
    cells scattered outside it (41 of 60 cells are zero). The resulting
    score ties are what makes CatBoost's sparse- and dense-layout
    tie-breaking diverge (catboost-8z4.46), unlike build_dense()'s
    ~40%-filled, non-degenerate matrix.
    """
    rng = np.random.RandomState(8)
    dense = np.zeros((DEGENERATE_N_ROWS, DEGENERATE_N_COLS))
    dense[:, 0] = np.round(rng.randn(DEGENERATE_N_ROWS), 3)
    extra_positions = set()
    while len(extra_positions) < 3:
        row = rng.randint(0, DEGENERATE_N_ROWS)
        col = rng.randint(1, DEGENERATE_N_COLS)
        extra_positions.add((row, col))
    for row, col in extra_positions:
        value = np.round(rng.randn(), 3)
        if value == 0:
            value = 0.5
        dense[row, col] = value
    return dense


def train_and_predict(data, train_dir, label):
    pool = Pool(data, label)
    model = CatBoost(dict(PARAMS, train_dir=os.path.join(SCRIPT_DIR, train_dir)))
    model.fit(pool)
    return pool, [float(v) for v in model.predict(pool, prediction_type="RawFormulaVal")]


def generate(dense, label, params, fixture_path, train_dir_tag, total_cells):
    csr = sp.csr_matrix(dense)

    sparse_pool, sparse_predict = train_and_predict(csr, f".catboost_train_{train_dir_tag}", label)
    _, dense_predict = train_and_predict(dense, f".catboost_train_{train_dir_tag}_dense", label)

    max_sparse_dense_delta = float(np.max(np.abs(np.array(sparse_predict) - np.array(dense_predict))))

    fixture = {
        "catboost_version": catboost.__version__,
        "params": params,
        "inputs": {
            "dense": [[float(v) for v in row] for row in dense],
            "label": label,
            "nnz": int(csr.nnz),
        },
        "expected": {
            "num_row": int(sparse_pool.num_row()),
            "num_col": int(sparse_pool.num_col()),
            "features": [[float(v) for v in row] for row in np.asarray(sparse_pool.get_features())],
            "feature_names": list(sparse_pool.get_feature_names()),
            "label": [float(v) for v in sparse_pool.get_label()],
            "predict": sparse_predict,
            "dense_predict": dense_predict,
            "max_sparse_dense_delta": max_sparse_dense_delta,
        },
    }

    with open(fixture_path, "w") as f:
        json.dump(fixture, f, indent=2)
        f.write("\n")

    print(f"catboost.__version__={catboost.__version__}", file=sys.stderr)
    print(f"nnz={csr.nnz} of {total_cells}", file=sys.stderr)
    print(f"max_sparse_dense_delta={max_sparse_dense_delta}", file=sys.stderr)
    print(f"predict[:3]={sparse_predict[:3]}", file=sys.stderr)
    print("OK", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--degenerate", action="store_true",
                         help="generate the degenerate tie-heavy fixture instead of the default one")
    args = parser.parse_args()

    os.makedirs(FIXTURE_DIR, exist_ok=True)

    if args.degenerate:
        dense = build_dense_degenerate()
        label = [int(dense[i, 0] > 0) for i in range(DEGENERATE_N_ROWS)]
        generate(dense, label, DEGENERATE_PARAMS, DEGENERATE_FIXTURE_PATH, "sparse_degenerate",
                 DEGENERATE_N_ROWS * DEGENERATE_N_COLS)
    else:
        dense = build_dense()
        label = [int(dense[i, 0] + dense[i, 1] > 0) for i in range(N_ROWS)]
        generate(dense, label, PARAMS, FIXTURE_PATH, "sparse", N_ROWS * N_COLS)


if __name__ == "__main__":
    main()
