// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// cpp11probe.cpp
int cpp11_scalar();
extern "C" SEXP _probepkg_cpp11_scalar() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp11_scalar());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_probepkg_cpp11_scalar", (DL_FUNC) &_probepkg_cpp11_scalar, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_probepkg(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
