#!/usr/bin/env bash
# Regenerate the CLI oracle smoke fixture from the pinned catboost binary.
# Mirrors tools/oracle/gen_smoke_fixture.py's role on the Python side (I2):
# previously only acquire.sh was committed and the fixture files under
# tests/fixtures/oracle-cli/ had no producing script.
#
# The 40-row dataset is *reused* from the Python oracle's generator, not
# regenerated independently: catboost-8z4.4-report.md records this as
# deliberate ("same data used by the sibling Python-oracle ticket for
# cross-oracle comparability"). Run tools/oracle/gen_smoke_fixture.py first
# if tests/fixtures/oracle/smoke_data.csv needs regenerating.
#
# Usage: tools/oracle/cli/gen_smoke_fixture.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
BIN="${SCRIPT_DIR}/bin/catboost-v1.2.10"
PY_FIXTURE_DIR="${REPO_ROOT}/tests/fixtures/oracle"
OUT_DIR="${REPO_ROOT}/tests/fixtures/oracle-cli"

if [[ ! -x "${BIN}" ]]; then
  echo "FATAL: ${BIN} not found. Run tools/oracle/cli/acquire.sh first." >&2
  exit 1
fi
if [[ ! -f "${PY_FIXTURE_DIR}/smoke_data.csv" ]]; then
  echo "FATAL: ${PY_FIXTURE_DIR}/smoke_data.csv not found. Run" >&2
  echo "  uv run --frozen --project tools/oracle python tools/oracle/gen_smoke_fixture.py" >&2
  echo "first -- the CLI fixture reuses that dataset for cross-oracle comparability." >&2
  exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

cp "${PY_FIXTURE_DIR}/smoke_data.csv" "${WORK_DIR}/smoke_data.csv"
printf '2\tCateg\tcat1\n3\tLabel\ttarget\n' > "${WORK_DIR}/smoke.cd"

(
  cd "${WORK_DIR}"
  "${BIN}" fit \
    --learn-set smoke_data.csv --column-description smoke.cd --delimiter , \
    --has-header --loss-function Logloss -i 20 --depth 4 --learning-rate 0.1 \
    --random-seed 42 -T 1 --model-file smoke_model.cbm --logging-level Silent
  "${BIN}" calc \
    --input-path smoke_data.csv --column-description smoke.cd --delimiter , \
    --has-header -m smoke_model.cbm --output-path smoke_predictions.tsv \
    --prediction-type RawFormulaVal,Probability
)

mkdir -p "${OUT_DIR}"
cp "${WORK_DIR}/smoke_data.csv" "${OUT_DIR}/smoke_data.csv"
cp "${WORK_DIR}/smoke.cd" "${OUT_DIR}/smoke.cd"
cp "${WORK_DIR}/smoke_model.cbm" "${OUT_DIR}/smoke_model.cbm"

python3 "${SCRIPT_DIR}/tsv_to_json.py" "${WORK_DIR}/smoke_predictions.tsv" "${OUT_DIR}/smoke_predictions.json"

python3 -m json.tool --indent 2 > "${OUT_DIR}/smoke_params.json" <<'EOF'
{"loss_function":"Logloss","iterations":20,"depth":4,"learning_rate":0.1,"random_seed":42,"verbose":false,"cli_args":{"--learn-set":"smoke_data.csv","--column-description":"smoke.cd","--delimiter":",","--has-header":true,"--loss-function":"Logloss","-i":20,"--depth":4,"--learning-rate":0.1,"--random-seed":42,"-T":1,"--model-file":"smoke_model.cbm","--logging-level":"Silent"}}
EOF

echo "Wrote ${OUT_DIR}/{smoke_data.csv,smoke.cd,smoke_model.cbm,smoke_predictions.json,smoke_params.json}"
echo "smoke_metadata.json is not regenerated by this script (it records acquisition"
echo "provenance and the determinism check, not per-run output) -- update it by hand"
echo "if the commands above change."
