#!/usr/bin/env bash
# Regenerate the CLI oracle fixtures for `roc --label-border` (catboost-hpk.3
# / catboost-ahs): non-default LabelBinarizationBorder runs of mode_roc,
# proving catboost.get_roc_curve()'s new label_border argument matches the
# CLI's --label-border/-b (vendor/catboost/catboost/app/mode_roc.cpp:34-37).
#
# Uses a dedicated dataset (label_border_data.csv, generated by
# make_label_border_data.py) with a continuous [0, 1] soft-label target
# cycling through {0.1, 0.4, 0.6, 0.9} -- smoke_data.csv's target is already
# hard 0/1, so a 0.5 vs 0.3 border would binarize it identically and the
# fixture would silently fail to exercise the new argument at all. Two roc
# runs (border 0.5 == the pre-existing default, and border 0.3) are
# generated from the same trained model / eval file so the R test can
# compare catboost.get_roc_curve(model, pool, label_border = 0.3) against a
# fixture that actually differs from the default-border curve.
#
# Usage: tools/oracle/cli/gen_roc_label_border_fixture.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
BIN="${SCRIPT_DIR}/bin/catboost-v1.2.10"
FIXTURE_DIR="${REPO_ROOT}/tests/fixtures/oracle-cli"

if [[ ! -x "${BIN}" ]]; then
  echo "FATAL: ${BIN} not found. Run tools/oracle/cli/acquire.sh first." >&2
  exit 1
fi

python3 "${SCRIPT_DIR}/make_label_border_data.py"
cp "${FIXTURE_DIR}/smoke.cd" "${FIXTURE_DIR}/label_border.cd"

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

(
  cd "${WORK_DIR}"
  "${BIN}" fit \
    --learn-set "${FIXTURE_DIR}/label_border_data.csv" \
    --column-description "${FIXTURE_DIR}/label_border.cd" --delimiter , \
    --has-header --loss-function CrossEntropy -i 20 --depth 4 --learning-rate 0.1 \
    --random-seed 42 -T 1 --model-file label_border_model.cbm --logging-level Silent
  "${BIN}" calc \
    --input-path "${FIXTURE_DIR}/label_border_data.csv" \
    --column-description "${FIXTURE_DIR}/label_border.cd" --delimiter , \
    --has-header -m label_border_model.cbm --output-path eval_result.tsv \
    --output-columns Label,RawFormulaVal -T 1
  "${BIN}" roc \
    --eval-file eval_result.tsv --label-border 0.5 \
    --output-path roc_data_label_border_default.tsv -T 1
  "${BIN}" roc \
    --eval-file eval_result.tsv --label-border 0.3 \
    --output-path roc_data_label_border_0.3.tsv -T 1
)

cp "${WORK_DIR}/roc_data_label_border_default.tsv" "${FIXTURE_DIR}/roc_data_label_border_default.tsv"
cp "${WORK_DIR}/roc_data_label_border_0.3.tsv" "${FIXTURE_DIR}/roc_data_label_border_0.3.tsv"

echo "Wrote ${FIXTURE_DIR}/roc_data_label_border_default.tsv (--label-border 0.5)"
echo "Wrote ${FIXTURE_DIR}/roc_data_label_border_0.3.tsv (--label-border 0.3)"
