context("test_params_validation.R")

# P5.5 (catboost-8z4.62) -- catboost.train/catboost.cv reject unknown
# `params` list keys, unless the caller opts out via
# options(catboostr.allow_unknown_params = TRUE). See validate_params_keys()
# and .catboostr_known_params in R/catboost.R (the latter is generated by
# tools/parity/gen_param_reference.py from the machine-generated capability
# inventory, tests/fixtures/parity/matrix.dispositioned.json).

pool <- catboost.load_pool(
  matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), ncol = 1),
  label = c(0, 1, 0, 1, 0, 1, 0, 1, 0, 1)
)

tiny_params <- function(extra = list()) {
  # NB: native's flat "verbose" option is an integer print-period (see
  # output_file_options.cpp's VerbosePeriod("verbose", 1)), not a boolean --
  # logging_level = "Silent" is the correct way to silence training here.
  utils::modifyList(
    list(loss_function = "Logloss", iterations = 2, logging_level = "Silent", thread_count = 1),
    extra
  )
}

test_that("catboost.train: a canonical params key trains without error", {
  expect_silent(catboost.train(pool, params = tiny_params(list(depth = 3))))
})

test_that("params key 'silent' is translated to logging_level before export (catboost-8z4.122, matrix row goes green)", {
  # 'silent' is Python-client-side sugar for logging_level (core.py's
  # _process_verbose(), never a native flat option itself -- confirmed by
  # the "Python-only params keys" test below still rejecting it if it ever
  # reached native unmodified). prepare_train_export_parameters() now
  # translates it before JSON export, so silent = TRUE/FALSE trains exactly
  # as logging_level = "Silent"/"Verbose" would. Kept right after the
  # canonical-training test above (not next to the deliberately-erroring
  # red-row tests further down this file), because CatBoost's native global
  # logger singleton (TCatboostLog::ResetBackend, logging.cpp) only suppresses
  # its own "Custom logger is already specified" cross-talk warning while
  # LogPriority is still at the *previous* successful call's level -- a
  # training call that errors before that gets set leaves the singleton
  # noisier for whatever call comes right after it, unrelated to this fix.
  expect_silent(catboost.train(pool, params = tiny_params(list(logging_level = NULL, silent = TRUE))))
  expect_output(
    catboost.train(pool, params = tiny_params(list(logging_level = NULL, silent = FALSE))),
    "learn:"
  )
  expect_error(
    catboost.train(pool, params = tiny_params(list(silent = TRUE))),
    "Only one of the parameters"
  )
  expect_error(
    catboost.train(pool, params = tiny_params(list(logging_level = NULL, silent = "yes"))),
    "'silent' must be a single TRUE/FALSE"
  )
})

test_that("catboost.pool.quantize: also reaches validate_params_keys() via process_synonyms(), and its documented params all pass (review-round fix)", {
  # catboost.pool.quantize()'s own roxygen doc names exactly 5 accepted
  # params: border_count (already covered by test_pool_quantization.R),
  # feature_border_type, nan_mode, per_float_feature_quantization, and
  # ignored_features -- all 5 are already members of .catboostr_known_params
  # (they're each also `catboost.train` params), so this call site is a
  # strict subset of the already-covered accepted-key set, not a gap.
  q_pool <- catboost.load_pool(
    matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), ncol = 1),
    label = c(0, 1, 0, 1, 0, 1, 0, 1, 0, 1)
  )
  expect_error(
    catboost.pool.quantize(q_pool, params = list(
      feature_border_type = "GreedyLogSum", nan_mode = "Min",
      per_float_feature_quantization = list("0:border_count=32"),
      ignored_features = list()
    )),
    NA
  )
  expect_true(catboost.pool.is_quantized(q_pool))
})

test_that("catboost.train: an unknown params key is rejected with a clear message", {
  expect_error(
    catboost.train(pool, params = tiny_params(list(depht = 3))),
    "Unknown catboost 'params' key.*depht"
  )
})

test_that("catboost.train: the escape hatch (options(catboostr.allow_unknown_params = TRUE)) bypasses R's own gate", {
  withr_options <- options(catboostr.allow_unknown_params = TRUE)
  on.exit(options(withr_options), add = TRUE)
  # "a_future_vendor_param" isn't a real native option either, so training
  # still errors downstream in native code -- the point of this assertion is
  # that it is *not* R's own gate rejecting it anymore (a real not-yet-known
  # vendor param would sail through this same path and train normally).
  err <- tryCatch({
    catboost.train(pool, params = tiny_params(list(a_future_vendor_param = 1)))
    NULL
  }, error = function(e) conditionMessage(e))
  expect_false(is.null(err))
  expect_false(grepl("Unknown catboost 'params' key", err, fixed = TRUE))
})

test_that("catboost.train: the escape hatch is off by default (second unknown-key check, isolated from prior test's on.exit)", {
  expect_error(
    catboost.train(pool, params = tiny_params(list(a_future_vendor_param = 1))),
    "Unknown catboost 'params' key"
  )
})

test_that("catboost.train: a duplicate params key (e.g. from c(list(...), list(...))) is rejected before JSON export (catboost-8z4.98)", {
  # jsonlite::toJSON(list(a=1,b=2,a=1)) silently synthesizes a key.1 name
  # (e.g. {"a":1,"b":2,"a.1":1}) instead of erroring, which native CatBoost's
  # C++ options parser then rejects (or, worse, silently ignores) -- catch it
  # at the R level, naming the offending key, before that JSON export happens.
  dup_params <- c(list(logging_level = "Silent"), tiny_params(list(logging_level = "Verbose")))
  expect_error(
    catboost.train(pool, params = dup_params),
    "Duplicate 'params' key.*logging_level"
  )
})

test_that("catboost.train: a duplicate key on a process_synonyms alias-group name is also rejected, not silently collapsed (batch review finding)", {
  # process_synonyms_in_one_group() silently drops all but the FIRST
  # occurrence of a duplicated alias-group name (e.g. two 'iterations'
  # entries) before validate_params_keys() ever runs -- unlike the
  # non-alias 'logging_level' case above, this bypassed the check entirely
  # until check_no_duplicate_params_keys() was hoisted to the top of
  # process_synonyms(). 'iterations' is one of the 24 alias-group names.
  dup_params <- c(list(iterations = 5), tiny_params(list(iterations = 9)))
  expect_error(
    catboost.train(pool, params = dup_params),
    "Duplicate 'params' key.*iterations"
  )
})

# --- Blocked-capability closures (review-round fix) ---------------------
# These params keys are accepted by R's *own* unknown-key gate (they are in
# .catboostr_known_params) but the underlying capability does not actually
# work in R for a specific, verified reason -- so the matrix rows for these
# names stay RED (spec Sec 4.4: a blocked/skipped differential test must
# never be marked green), matching the mode:model-based-eval precedent
# exactly. Each assertion below is a REAL training call asserting the
# SPECIFIC native error text, not merely "not R's own gate error" (the
# earlier `expect_gate_accepts_key` helper was circular: since the accepted
# set is generated from the same 139-name inventory the matrix rows live in,
# every one of those 139 names trivially passes it by construction, proving
# nothing about whether the capability actually works).

test_that("params key 'fixed_binary_splits' is rejected by native on CPU (matrix row stays red)", {
  expect_error(
    catboost.train(pool, params = tiny_params(list(fixed_binary_splits = list(0L)))),
    "fixed_binary_splits is unimplemented for task type CPU"
  )
})

test_that("params key 'scale_pos_weight' hits a native metric-construction bug even embedded correctly in loss_function (matrix row stays red)", {
  # scale_pos_weight is not a flat top-level option (Python's client only
  # gets away with the convenience kwarg by embedding it into the
  # loss_function description string, e.g. "Logloss:scale_pos_weight=1.5");
  # doing the same from R still fails, because CatBoost derives the default
  # eval_metric from the same description and metric construction (unlike
  # loss construction) rejects the scale_pos_weight parameter -- reproducible
  # even with eval_metric explicitly overridden to a bare "Logloss".
  expect_error(
    catboost.train(pool, params = tiny_params(list(
      loss_function = "Logloss:scale_pos_weight=1.5", eval_metric = "Logloss"
    ))),
    "Logloss metric shouldn't have scale_pos_weight parameter"
  )
})

test_that("params key 'input_borders' is rejected as an unknown flat option (matrix row stays red)", {
  # Unlike output_borders (a real flat option -- output_file_options.cpp
  # OutputBordersFileName -- see test_param_family_coverage.R), input_borders
  # is only ever consumed by Python's Pool.quantize() pre-processing step,
  # never by the general PlainJsonToOptions flat-option parser that
  # catboost.train's params blob goes through in either language.
  expect_error(
    catboost.train(pool, params = tiny_params(list(input_borders = tempfile()))),
    "Unknown option \\{input_borders\\}"
  )
})

test_that("catboost.load_pool: 'graph' is accepted syntactically but the R Pool-construction glue can't build a graph+group_id Pool (matrix row stays red)", {
  # graph is a real catboost.load_pool() argument (R/catboost.R:110) and a
  # real Python Pool(graph=...) argument too, and requires nontrivial groups
  # in both languages ("Graph features require nontrivial groups",
  # data_providers.cpp:494). Reproduced directly (review-round fix): building
  # a Pool with both graph= and group_id= set throws a hard native error from
  # the R glue's own data.frame path (catboost.from_data_frame ->
  # catboost.from_matrix -> data_provider_builders.cpp), not from Python
  # parity logic -- an under-exercised combination in catboostr's own C
  # bridge (further probing found additional graph/group_id argument-type
  # coercion errors in the plain-matrix path too, corroborating that this
  # specific combination is genuinely unimplemented/fragile here, not a
  # one-off).
  graph_pool_data <- data.frame(num1 = c(1, 2, 3, 4), num2 = c(5, 6, 7, 8))
  expect_error(
    catboost.load_pool(graph_pool_data, label = c(0, 1, 0, 1),
                        group_id = c(0L, 0L, 1L, 1L),
                        graph = matrix(c(1L, 2L, 3L, 4L), ncol = 2)),
    "Internal CatBoost Error|Unimplemented|INTEGER\\(\\)|REAL\\(\\)"
  )
})

test_that("GPU-only params keys fail without a CUDA device, matching the mode:model-based-eval precedent (matrix rows stay red)", {
  # Each key needs a syntactically valid value so the failure genuinely comes
  # from "no CUDA device", not from a value-parsing error one layer earlier.
  gpu_only_values <- list(
    devices = "0",
    device_config = "0",
    gpu_cat_features_storage = "GpuRam",
    gpu_ram_part = 0.5,
    pinned_memory_size = "1gb",
    random_score_type = "NormalWithModelSizeDecrease"
  )
  for (k in names(gpu_only_values)) {
    extra <- setNames(list(gpu_only_values[[k]]), k)
    extra$task_type <- "GPU"
    expect_error(
      catboost.train(pool, params = tiny_params(extra)),
      "Environment for task type \\[GPU\\] not found|CUDA|Can't load GPU learning library",
      info = k
    )
  }
})

test_that("Python-only params keys with no catboostr equivalent are rejected by native (matrix rows stay red)", {
  # 'callback' (singular) is not a real Python kwarg either (unlike
  # 'callbacks', see the test below) nor a native flat option -- there is no
  # capability of any kind behind this key in either language, verified by
  # grepping catboost/python-package/catboost/core.py and
  # plain_options_helper.cpp for it (catboost-8z4.122 re-verification).
  no_r_equivalent_keys <- c("callback", "plot", "plot_file", "log_cout", "log_cerr")
  for (k in no_r_equivalent_keys) {
    extra <- setNames(list("x"), k)
    expect_error(
      catboost.train(pool, params = tiny_params(extra)),
      paste0("Unknown option \\{", k, "\\}"),
      info = k
    )
  }
})

test_that("params key 'callbacks' invokes a real per-iteration native callback (catboost-8z4.122, matrix row goes green)", {
  # r_train_callbacks.h/.cpp wires params$callbacks into the same native
  # ITrainingCallbacks/TCustomCallbackDescriptor::AfterIterationFunc hook
  # Python's `callbacks` kwarg uses (train_model.h; _catboost.pyx's
  # _BuildCustomCallbackDescritor) -- this is a real per-iteration training
  # callback, not just syntactic acceptance.
  seen_iterations <- integer(0)
  record_iteration <- function(info) {
    seen_iterations <<- c(seen_iterations, info$iteration)
    TRUE
  }
  model <- catboost.train(pool, params = tiny_params(list(iterations = 5, callbacks = list(record_iteration))))
  expect_equal(seen_iterations, 1:5)
  expect_true(is.list(model))

  # info$metrics has the same shape as catboost.get_evals_result()'s return
  # value (both come from the identical TMetricsAndTimeLeftHistory::
  # SaveMetrics() JSON, see r_train_callbacks.cpp) -- learn Logloss should be
  # present and growing by one value per iteration seen so far.
  seen_metric_lengths <- integer(0)
  record_metric_length <- function(info) {
    seen_metric_lengths <<- c(seen_metric_lengths, length(info$metrics$learn$Logloss))
    TRUE
  }
  catboost.train(pool, params = tiny_params(list(iterations = 3, callbacks = list(record_metric_length))))
  expect_equal(seen_metric_lengths, 1:3)

  # A callback returning FALSE stops training early -- all()-of-callbacks
  # semantics, matching Python's _TrainCallbacksWrapper.
  stop_after_two <- function(info) info$iteration < 2
  model_stopped_early <- catboost.train(
    pool, params = tiny_params(list(iterations = 10, callbacks = list(stop_after_two)))
  )
  expect_equal(model_stopped_early$tree_count, 2)

  # all()-of-callbacks: training stops as soon as ANY callback returns FALSE,
  # even if an earlier one in the list would have said continue.
  always_true <- function(info) TRUE
  model_multi_callback <- catboost.train(
    pool, params = tiny_params(list(iterations = 10, callbacks = list(always_true, stop_after_two)))
  )
  expect_equal(model_multi_callback$tree_count, 2)
})

test_that("params keys 'classes_count'/'class_names' can't be exercised for MultiClass string labels: catboost.load_pool pre-converts labels client-side (matrix rows stay red)", {
  mc_pool <- catboost.load_pool(
    matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), ncol = 1),
    label = c("neg", "pos", "neg", "pos", "neg", "pos", "neg", "pos", "neg", "pos")
  )
  expect_error(
    catboost.train(mc_pool, params = list(
      loss_function = "MultiClass", iterations = 2, logging_level = "Silent",
      thread_count = 1, classes_count = 2, class_names = list("neg", "pos")
    )),
    "Not all class names are numeric, but specified target data is"
  )
})

test_that("catboost.cv: an unknown params key is rejected the same way as catboost.train", {
  expect_error(
    catboost.cv(pool, params = tiny_params(list(depht = 3)), fold_count = 2),
    "Unknown catboost 'params' key.*depht"
  )
})

test_that("catboost.cv: a canonical params key (including one set by early_stopping_rounds) validates", {
  expect_error(
    catboost.cv(pool, params = tiny_params(), fold_count = 2, early_stopping_rounds = 5),
    NA
  )
})

# --- catboost-8z4.100: catboost.eval_feature/catboost.model_based_eval ------
# previously called prepare_train_export_parameters(params) directly with no
# validate_params_keys()/process_synonyms() call at all. Neither function
# documents or tests accepting process_synonyms() alias spellings (their
# roxygen docs just point to catboost.train's own params reference), so they
# follow the catboost.cv precedent exactly: validate_params_keys() directly,
# no process_synonyms() resolution.

test_that("catboost.eval_feature: an unknown params key is rejected the same way as catboost.train", {
  expect_error(
    catboost.eval_feature(pool, features_to_evaluate = list(),
                           params = tiny_params(list(depht = 3)),
                           relative_fold_size = 0.5),
    "Unknown catboost 'params' key.*depht"
  )
})

test_that("catboost.eval_feature: a duplicate params key is rejected before JSON export", {
  dup_params <- c(list(logging_level = "Silent"), tiny_params(list(logging_level = "Verbose")))
  expect_error(
    catboost.eval_feature(pool, features_to_evaluate = list(),
                           params = dup_params, relative_fold_size = 0.5),
    "Duplicate 'params' key.*logging_level"
  )
})

model_based_eval_fixture_paths <- function() {
  list(data = testthat::test_path("..", "fixtures", "oracle-cli", "smoke_data.csv"),
       cd = testthat::test_path("..", "fixtures", "oracle-cli", "smoke.cd"))
}

test_that("catboost.model_based_eval: an unknown params key is rejected the same way as catboost.train", {
  fx <- model_based_eval_fixture_paths()
  expect_error(
    catboost.model_based_eval(
      learn_set = fx$data, test_set = fx$data, features_to_evaluate = "0",
      column_description = fx$cd,
      params = list(depht = 3, logging_level = "Silent", task_type = "GPU")
    ),
    "Unknown catboost 'params' key.*depht"
  )
})

test_that("catboost.model_based_eval: a duplicate params key is rejected before JSON export", {
  fx <- model_based_eval_fixture_paths()
  dup_params <- c(list(logging_level = "Silent"),
                   list(logging_level = "Verbose", task_type = "GPU"))
  expect_error(
    catboost.model_based_eval(
      learn_set = fx$data, test_set = fx$data, features_to_evaluate = "0",
      column_description = fx$cd, params = dup_params
    ),
    "Duplicate 'params' key.*logging_level"
  )
})

# --- One regression case per process_synonyms_in_one_group() alias group ---
# (R/catboost.R:~2620-2632) -- every alias name must still validate and train
# successfully post-P5.5, matching the pre-P5.5 (unvalidated) behavior.
synonym_groups <- list(
  c("loss_function", "objective"),
  c("iterations", "n_estimators", "num_boost_round", "num_trees"),
  c("learning_rate", "eta"),
  c("random_seed", "random_state"),
  c("l2_leaf_reg", "reg_lambda"),
  c("depth", "max_depth"),
  c("min_data_in_leaf", "min_child_samples"),
  c("max_leaves", "num_leaves"),
  c("rsm", "colsample_bylevel"),
  c("border_count", "max_bin"),
  c("verbose", "verbose_eval")
)

for (group in synonym_groups) {
  for (alias in group) {
    local({
      alias <- alias
      group <- group
      test_that(paste0("catboost.train: alias '", alias, "' (group [", paste(group, collapse = ", "),
                        "]) still validates and trains after P5.5"), {
        extra <- list()
        extra[[alias]] <- if (alias %in% c("loss_function", "objective")) "Logloss"
          else if (alias %in% c("verbose", "verbose_eval")) 1L  # native "verbose" is an int print-period, not a bool
          else if (alias %in% c("depth", "max_depth")) 3
          else if (alias %in% c("iterations", "n_estimators", "num_boost_round", "num_trees")) 2
          else if (alias %in% c("learning_rate", "eta")) 0.1
          else if (alias %in% c("random_seed", "random_state")) 0
          else if (alias %in% c("l2_leaf_reg", "reg_lambda")) 3
          else if (alias %in% c("min_data_in_leaf", "min_child_samples")) 1
          else if (alias %in% c("max_leaves", "num_leaves")) 8
          else if (alias %in% c("rsm", "colsample_bylevel")) 0.9
          else if (alias %in% c("border_count", "max_bin")) 32
          else stop("unhandled alias in test setup: ", alias)

        base <- list(loss_function = "Logloss", iterations = 2, logging_level = "Silent", thread_count = 1)
        if (alias %in% c("loss_function", "objective")) base$loss_function <- NULL
        if (alias %in% c("iterations", "n_estimators", "num_boost_round", "num_trees")) base$iterations <- NULL
        params <- utils::modifyList(base, extra)
        if (alias %in% c("max_leaves", "num_leaves")) params$grow_policy <- "Lossguide"

        expect_silent(catboost.train(pool, params = params))
      })
    })
  }
}
