context("test_params_validation.R")

# P5.5 (catboost-8z4.62) -- catboost.train/catboost.cv reject unknown
# `params` list keys, unless the caller opts out via
# options(catboostr.allow_unknown_params = TRUE). See validate_params_keys()
# and .catboostr_known_params in R/catboost.R (the latter is generated by
# tools/parity/gen_param_reference.py from the machine-generated capability
# inventory, tests/fixtures/parity/matrix.dispositioned.json).

pool <- catboost.load_pool(
  matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), ncol = 1),
  label = c(0, 1, 0, 1, 0, 1, 0, 1, 0, 1)
)

tiny_params <- function(extra = list()) {
  # NB: native's flat "verbose" option is an integer print-period (see
  # output_file_options.cpp's VerbosePeriod("verbose", 1)), not a boolean --
  # logging_level = "Silent" is the correct way to silence training here.
  utils::modifyList(
    list(loss_function = "Logloss", iterations = 2, logging_level = "Silent", thread_count = 1),
    extra
  )
}

test_that("catboost.train: a canonical params key trains without error", {
  expect_silent(catboost.train(pool, params = tiny_params(list(depth = 3))))
})

test_that("catboost.train: an unknown params key is rejected with a clear message", {
  expect_error(
    catboost.train(pool, params = tiny_params(list(depht = 3))),
    "Unknown catboost 'params' key.*depht"
  )
})

test_that("catboost.train: the escape hatch (options(catboostr.allow_unknown_params = TRUE)) bypasses R's own gate", {
  withr_options <- options(catboostr.allow_unknown_params = TRUE)
  on.exit(options(withr_options), add = TRUE)
  # "a_future_vendor_param" isn't a real native option either, so training
  # still errors downstream in native code -- the point of this assertion is
  # that it is *not* R's own gate rejecting it anymore (a real not-yet-known
  # vendor param would sail through this same path and train normally).
  err <- tryCatch({
    catboost.train(pool, params = tiny_params(list(a_future_vendor_param = 1)))
    NULL
  }, error = function(e) conditionMessage(e))
  expect_false(is.null(err))
  expect_false(grepl("Unknown catboost 'params' key", err, fixed = TRUE))
})

test_that("catboost.train: the escape hatch is off by default (second unknown-key check, isolated from prior test's on.exit)", {
  expect_error(
    catboost.train(pool, params = tiny_params(list(a_future_vendor_param = 1))),
    "Unknown catboost 'params' key"
  )
})

# --- Acceptance-only closures: these keys are recognized by the R-side gate
# (proving `catboost.train` doesn't reject them as unknown) but are not
# numerically diffed against a Python oracle -- see task-5-report.md for why
# each one isn't (not a flat top-level native option / architecture
# limitation / GPU-only / declarative-config-only).
expect_gate_accepts_key <- function(extra) {
  err <- tryCatch({
    catboost.train(pool, params = tiny_params(extra))
    NULL
  }, error = function(e) conditionMessage(e))
  # Whatever happens downstream (success, or a *native* error) is fine here;
  # the only thing under test is that R's own unknown-key gate let it through.
  expect_true(is.null(err) || !grepl("Unknown catboost 'params' key", err, fixed = TRUE))
}

test_that("catboost.train: params key 'used_ram_limit' is accepted by R's own gate", {
  expect_gate_accepts_key(list(used_ram_limit = "512mb"))
})

test_that("catboost.train: params key 'scale_pos_weight' is accepted by R's own gate (native rejects it as a flat option; belongs in the loss_function description string instead)", {
  expect_gate_accepts_key(list(scale_pos_weight = 1.5))
})

test_that("catboost.train: params keys 'classes_count'/'class_names' are accepted by R's own gate (catboost.load_pool pre-converts string labels to numeric indices client-side, an R-Pool-architecture limitation)", {
  expect_gate_accepts_key(list(classes_count = 2, class_names = list("neg", "pos")))
})

test_that("catboost.train: params keys 'input_borders'/'output_borders' are accepted by R's own gate (native rejects them as flat top-level options in this vendor version)", {
  expect_gate_accepts_key(list(input_borders = tempfile()))
  expect_gate_accepts_key(list(output_borders = tempfile()))
})

test_that("catboost.cv: an unknown params key is rejected the same way as catboost.train", {
  expect_error(
    catboost.cv(pool, params = tiny_params(list(depht = 3)), fold_count = 2),
    "Unknown catboost 'params' key.*depht"
  )
})

test_that("catboost.cv: a canonical params key (including one set by early_stopping_rounds) validates", {
  expect_error(
    catboost.cv(pool, params = tiny_params(), fold_count = 2, early_stopping_rounds = 5),
    NA
  )
})

# --- One regression case per process_synonyms_in_one_group() alias group ---
# (R/catboost.R:~2620-2632) -- every alias name must still validate and train
# successfully post-P5.5, matching the pre-P5.5 (unvalidated) behavior.
synonym_groups <- list(
  c("loss_function", "objective"),
  c("iterations", "n_estimators", "num_boost_round", "num_trees"),
  c("learning_rate", "eta"),
  c("random_seed", "random_state"),
  c("l2_leaf_reg", "reg_lambda"),
  c("depth", "max_depth"),
  c("min_data_in_leaf", "min_child_samples"),
  c("max_leaves", "num_leaves"),
  c("rsm", "colsample_bylevel"),
  c("border_count", "max_bin"),
  c("verbose", "verbose_eval")
)

for (group in synonym_groups) {
  for (alias in group) {
    local({
      alias <- alias
      group <- group
      test_that(paste0("catboost.train: alias '", alias, "' (group [", paste(group, collapse = ", "),
                        "]) still validates and trains after P5.5"), {
        extra <- list()
        extra[[alias]] <- if (alias %in% c("loss_function", "objective")) "Logloss"
          else if (alias %in% c("verbose", "verbose_eval")) 1L  # native "verbose" is an int print-period, not a bool
          else if (alias %in% c("depth", "max_depth")) 3
          else if (alias %in% c("iterations", "n_estimators", "num_boost_round", "num_trees")) 2
          else if (alias %in% c("learning_rate", "eta")) 0.1
          else if (alias %in% c("random_seed", "random_state")) 0
          else if (alias %in% c("l2_leaf_reg", "reg_lambda")) 3
          else if (alias %in% c("min_data_in_leaf", "min_child_samples")) 1
          else if (alias %in% c("max_leaves", "num_leaves")) 8
          else if (alias %in% c("rsm", "colsample_bylevel")) 0.9
          else if (alias %in% c("border_count", "max_bin")) 32
          else stop("unhandled alias in test setup: ", alias)

        base <- list(loss_function = "Logloss", iterations = 2, logging_level = "Silent", thread_count = 1)
        if (alias %in% c("loss_function", "objective")) base$loss_function <- NULL
        if (alias %in% c("iterations", "n_estimators", "num_boost_round", "num_trees")) base$iterations <- NULL
        params <- utils::modifyList(base, extra)
        if (alias %in% c("max_leaves", "num_leaves")) params$grow_policy <- "Lossguide"

        expect_silent(catboost.train(pool, params = params))
      })
    })
  }
}
