#!/usr/bin/env python3
"""R1.2: render docs/PARITY.md from the dispositioned parity matrix.

Input:  tests/fixtures/parity/matrix.dispositioned.json (770 rows; already
        has tests/fixtures/parity/closure_overlay.json merged in by
        apply_disposition.py -- see that script's docstring. This script
        does not re-read closure_overlay.json: matrix.dispositioned.json is
        its post-merge output, so re-applying it here would be redundant,
        not more correct).
Output: docs/PARITY.md

Every row falls into exactly one `state` (spec-defined categories; as of
this writing only "green" and "red" occur in the fixture -- "other" is kept
as a group for any state value besides "green"/"red" the fixture might gain
later; it is not invented, just not currently populated).

Per-row reason text is never invented: it is `final_method_note` if present,
else `tolerance_justification` if present, else the literal string
"no note recorded".
"""
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MATRIX_PATH = REPO_ROOT / "tests/fixtures/parity/matrix.dispositioned.json"
OUTPUT_PATH = REPO_ROOT / "docs/PARITY.md"

NO_NOTE = "no note recorded"


def row_reason(row: dict) -> str:
    note = row.get("final_method_note")
    if note:
        return note
    justification = row.get("tolerance_justification")
    if justification:
        return justification
    return NO_NOTE


def group_by(rows: list, key: str) -> dict:
    groups: dict = {}
    for row in rows:
        groups.setdefault(row[key], []).append(row)
    return groups


def render(rows: list) -> str:
    by_state = group_by(rows, "state")
    green = by_state.pop("green", [])
    red = by_state.pop("red", [])
    other = [row for rows_ in by_state.values() for row in rows_]

    lines = []
    lines.append(
        "<!-- generated by tools/parity/render_summary.py; do not "
        "hand-edit. Regenerate: python3 tools/parity/render_summary.py -->"
    )
    lines.append("# catboostr Parity Matrix")
    lines.append("")
    lines.append(
        "Machine-derived summary of the CatBoost R/Python/CLI capability "
        "parity matrix (`tests/fixtures/parity/matrix.dispositioned.json`, "
        f"{len(rows)} rows). Every claim below traces to a field in that "
        "file -- nothing here is hand-written."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| State | Count |")
    lines.append("| --- | --- |")
    lines.append(f"| green | {len(green)} |")
    lines.append(f"| red | {len(red)} |")
    lines.append(f"| other | {len(other)} |")
    lines.append(f"| **Total** | {len(rows)} |")
    lines.append("")

    lines.append("## Red rows (not yet available)")
    lines.append("")
    lines.append(
        f"{len(red)} rows. Each entry is the capability's "
        "`inventory_row_id` and its recorded reason, verbatim from the "
        "matrix (`final_method_note`, falling back to "
        f"`tolerance_justification`, falling back to \"{NO_NOTE}\" if "
        "neither is recorded)."
    )
    lines.append("")
    for disposition, disp_rows in sorted(group_by(red, "disposition").items()):
        lines.append(f"### {disposition} ({len(disp_rows)})")
        lines.append("")
        for row in sorted(disp_rows, key=lambda r: r["inventory_row_id"]):
            lines.append(f"- `{row['inventory_row_id']}` -- {row_reason(row)}")
        lines.append("")

    if other:
        lines.append(f"## Other rows ({len(other)})")
        lines.append("")
        for state, state_rows in sorted(by_state.items()):
            lines.append(f"### state: {state} ({len(state_rows)})")
            lines.append("")
            for row in sorted(state_rows, key=lambda r: r["inventory_row_id"]):
                lines.append(f"- `{row['inventory_row_id']}` -- {row_reason(row)}")
            lines.append("")

    lines.append(f"## Green rows ({len(green)})")
    lines.append("")
    lines.append(
        "Covered by a passing differential test. Listed compactly by "
        "`inventory_row_id` -- see the red rows above for what's NOT yet "
        "covered, which is the more interesting information for a reader."
    )
    lines.append("")
    for disposition, disp_rows in sorted(group_by(green, "disposition").items()):
        ids = ", ".join(
            f"`{row['inventory_row_id']}`"
            for row in sorted(disp_rows, key=lambda r: r["inventory_row_id"])
        )
        lines.append(f"- **{disposition}** ({len(disp_rows)}): {ids}")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    rows = json.loads(MATRIX_PATH.read_text())
    OUTPUT_PATH.write_text(render(rows))
    print(f"wrote {OUTPUT_PATH}", file=sys.stderr)
    counts = group_by(rows, "state")
    print(
        json.dumps({state: len(rs) for state, rs in counts.items()}, indent=2),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
